[package]
name = "payverse_anchor"
version = "0.1.0"
edition = "2021"

[lib]
name = "payverse_anchor"
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = { version = "0.27.0", features = ["init-if-needed"] }
